name: vertretungsplan_mobile
description: The Vertretungsplan Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  url_launcher: ^5.4.2
  flutter_html: ^1.0.0
  device_info: ^1.0.0
  rflutter_alert: ^1.1.0
  flutter_launcher_icons: "^0.7.0"

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:

  assets:
    - assets/img/banner.jpg

    - assets/launcher/icon.png
    - assets/launcher/background.png
    - assets/launcher/foreground.png

  uses-material-design: true
